### ISSUE TITLE
Question about More Mountains

### ISSUE THREAD

**Issue by michaelheiml** [VirtueSky/nice-vibrations-unity#1]
Hi, is this an official re-release of the deprecated package from MoreMountains NiceVibrations? If so, does it work with current iOS 16? Because the last official release on Unity Asset Store doesn't work on iOS 16 any more.

**Comment by VirtueSky** [comment]
Hello! Thank you for asking the question.
I am very sorry for not fully updating the information about the
NiceVibrations package.
However, I have build and test it, it still works on ios 16.
